# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminauthentication.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdminAuthForm(object):
    def setupUi(self, AdminAuthForm):
        AdminAuthForm.setObjectName("AdminAuthForm")
        AdminAuthForm.resize(511, 287)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("auth_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AdminAuthForm.setWindowIcon(icon)
        AdminAuthForm.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"\n"
"QPushButton{\n"
"background-color: rgb(167, 205, 255);\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(AdminAuthForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pwdlineEdit = QtWidgets.QLineEdit(AdminAuthForm)
        self.pwdlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdlineEdit.setObjectName("pwdlineEdit")
        self.gridLayout.addWidget(self.pwdlineEdit, 1, 4, 1, 2)
        self.change_btn = QtWidgets.QPushButton(AdminAuthForm)
        self.change_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(167, 205, 255);\n"
"}")
        self.change_btn.setObjectName("change_btn")
        self.gridLayout.addWidget(self.change_btn, 2, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(AdminAuthForm)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(AdminAuthForm)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.user_lineEdit = QtWidgets.QLineEdit(AdminAuthForm)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.gridLayout.addWidget(self.user_lineEdit, 0, 4, 1, 2)
        self.signin_btn = QtWidgets.QPushButton(AdminAuthForm)
        self.signin_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(167, 205, 255);\n"
"}")
        self.signin_btn.setObjectName("signin_btn")
        self.gridLayout.addWidget(self.signin_btn, 2, 4, 1, 1)
        self.response_label = QtWidgets.QLabel(AdminAuthForm)
        self.response_label.setStyleSheet("color: rgb(255, 0, 0);\n"
"\n"
"QPushButton{\n"
"background-color: rgb(167, 205, 255);\n"
"}")
        self.response_label.setObjectName("response_label")
        self.gridLayout.addWidget(self.response_label, 3, 4, 1, 2, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(AdminAuthForm)
        QtCore.QMetaObject.connectSlotsByName(AdminAuthForm)
        AdminAuthForm.setTabOrder(self.user_lineEdit, self.pwdlineEdit)
        AdminAuthForm.setTabOrder(self.pwdlineEdit, self.signin_btn)
        AdminAuthForm.setTabOrder(self.signin_btn, self.change_btn)

    def retranslateUi(self, AdminAuthForm):
        _translate = QtCore.QCoreApplication.translate
        AdminAuthForm.setWindowTitle(_translate("AdminAuthForm", "Admin Authentication"))
        self.change_btn.setText(_translate("AdminAuthForm", "Change Password"))
        self.label_2.setText(_translate("AdminAuthForm", "Password:"))
        self.label.setText(_translate("AdminAuthForm", "Username:"))
        self.signin_btn.setText(_translate("AdminAuthForm", "Sign In"))
        self.signin_btn.setShortcut(_translate("AdminAuthForm", "Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminAuthForm = QtWidgets.QWidget()
    ui = Ui_AdminAuthForm()
    ui.setupUi(AdminAuthForm)
    AdminAuthForm.show()
    sys.exit(app.exec_())
