# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authenticationform.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(514, 390)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("auth_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.user_lineEdit = QtWidgets.QLineEdit(Form)
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.gridLayout.addWidget(self.user_lineEdit, 0, 4, 1, 2)
        self.pwdlineEdit = QtWidgets.QLineEdit(Form)
        self.pwdlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwdlineEdit.setObjectName("pwdlineEdit")
        self.gridLayout.addWidget(self.pwdlineEdit, 1, 4, 1, 2)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.signin_btn = QtWidgets.QPushButton(Form)
        self.signin_btn.setStyleSheet("background-color: rgb(167, 205, 255);")
        self.signin_btn.setObjectName("signin_btn")
        self.gridLayout.addWidget(self.signin_btn, 3, 4, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.admin_btn = QtWidgets.QPushButton(Form)
        self.admin_btn.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(116, 2, 255);")
        self.admin_btn.setObjectName("admin_btn")
        self.gridLayout.addWidget(self.admin_btn, 4, 4, 1, 2)
        self.change_btn = QtWidgets.QPushButton(Form)
        self.change_btn.setStyleSheet("background-color: rgb(167, 205, 255);")
        self.change_btn.setObjectName("change_btn")
        self.gridLayout.addWidget(self.change_btn, 3, 5, 1, 1)
        self.response_label = QtWidgets.QLabel(Form)
        self.response_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.response_label.setText("")
        self.response_label.setObjectName("response_label")
        self.gridLayout.addWidget(self.response_label, 5, 4, 1, 2, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "User Authentication"))
        self.label_2.setText(_translate("Form", "Password:"))
        self.signin_btn.setText(_translate("Form", "Sign In"))
        self.signin_btn.setShortcut(_translate("Form", "Return"))
        self.label.setText(_translate("Form", "Username:"))
        self.admin_btn.setText(_translate("Form", "Login as Admin"))
        self.change_btn.setText(_translate("Form", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
