# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changepwdform.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangePwdForm(object):
    def setupUi(self, ChangePwdForm):
        ChangePwdForm.setObjectName("ChangePwdForm")
        ChangePwdForm.resize(512, 400)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("auth_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ChangePwdForm.setWindowIcon(icon)
        ChangePwdForm.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.horizontalLayout = QtWidgets.QHBoxLayout(ChangePwdForm)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(ChangePwdForm)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.oldpwdlineEdit = QtWidgets.QLineEdit(ChangePwdForm)
        self.oldpwdlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.oldpwdlineEdit.setObjectName("oldpwdlineEdit")
        self.gridLayout.addWidget(self.oldpwdlineEdit, 1, 4, 1, 2)
        self.userlineEdit = QtWidgets.QLineEdit(ChangePwdForm)
        self.userlineEdit.setObjectName("userlineEdit")
        self.gridLayout.addWidget(self.userlineEdit, 0, 4, 1, 2)
        self.label_2 = QtWidgets.QLabel(ChangePwdForm)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.update_btn = QtWidgets.QPushButton(ChangePwdForm)
        self.update_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(167, 205, 255);\n"
"}")
        self.update_btn.setObjectName("update_btn")
        self.gridLayout.addWidget(self.update_btn, 4, 4, 1, 2)
        self.label_3 = QtWidgets.QLabel(ChangePwdForm)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(ChangePwdForm)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.newpwdlineEdit = QtWidgets.QLineEdit(ChangePwdForm)
        self.newpwdlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpwdlineEdit.setObjectName("newpwdlineEdit")
        self.gridLayout.addWidget(self.newpwdlineEdit, 2, 4, 1, 2)
        self.new2pwdlineEdit = QtWidgets.QLineEdit(ChangePwdForm)
        self.new2pwdlineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.new2pwdlineEdit.setObjectName("new2pwdlineEdit")
        self.gridLayout.addWidget(self.new2pwdlineEdit, 3, 4, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.response_label = QtWidgets.QLabel(ChangePwdForm)
        self.response_label.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.response_label.setObjectName("response_label")
        self.verticalLayout.addWidget(self.response_label)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(ChangePwdForm)
        QtCore.QMetaObject.connectSlotsByName(ChangePwdForm)

    def retranslateUi(self, ChangePwdForm):
        _translate = QtCore.QCoreApplication.translate
        ChangePwdForm.setWindowTitle(_translate("ChangePwdForm", "Password Management"))
        self.label.setText(_translate("ChangePwdForm", "Username:"))
        self.label_2.setText(_translate("ChangePwdForm", "Old Password:"))
        self.update_btn.setText(_translate("ChangePwdForm", "Update"))
        self.label_3.setText(_translate("ChangePwdForm", "New Password:"))
        self.label_4.setText(_translate("ChangePwdForm", "Re-enter New Password:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangePwdForm = QtWidgets.QWidget()
    ui = Ui_ChangePwdForm()
    ui.setupUi(ChangePwdForm)
    ChangePwdForm.show()
    sys.exit(app.exec_())
